### ISSUE TITLE
Geo coder - Exception Handling

### ISSUE THREAD

**Issue by IsaacBravo** [MilaNLProc/twitter-demographer#8] opened 2022-12-28 16:32 UTC
* Twitter Demographer version: latest
* Python version: 3.8.16
* Operating System: google colab, microsoft

### Description

Hello @vinid,

I'm running some tests on the colab version of the library and when I run this line of code `new_data = demo.infer(data)`, I get the following error message.

### What I Did

![image](https://user-images.githubusercontent.com/76662213/209842788-4b356064-e46b-4a66-b6a5-798f66e8f71f.png)

I am using the following ids: 111286401171748589568, 1112865414902636549.

Any help in this regard I would be very grateful.

**Comment by vcutrona** [comment] 2022-12-28 17:01
Hi @IsaacBravo, thanks for reporting this issue!

Well, I can't reproduce the issue if using both the ids you provided: for "111286401171748589568" I obtain "The `ids` query parameter value [111286401171748589568] is not valid". 

However, your error seems related to the second id (1112865414902636549). The problem is that the user location cannot be recognized by OSM (the location is "I checked the box"), which returns "None". Thus, the application crashes when accessing the None value returned by Nominatim (see the if statement in line 42, which expects "g" to be an iterable). We need to add a safeguard before accessing that value.

Thanks again for your report -- we'll fix this issue very soon!

**Comment by IsaacBravo** [comment] 2022-12-28 18:26
Thank you @vcutrona for your reply! Makes sense. Also, I don't know if it's possible to incorporate a safeguard when an id is not valid? Because when checking large numbers of ids, it is possible that there are some invalid ones.

Sorry for the question, but how can I find out when there is a new update for the package? For example, one that incorporates this safeguard.

**Comment by vinid** [comment] 2023-01-05 03:56
Hello @IsaacBravo!

sorry for the slow replies! I should be able to work on this issue next week! I'll ping you when the fix is ready!

Federico

**Comment by vinid** [comment] 2023-01-10 18:59
the bug should be fixed (works with id `1112865414902636549`), the edit is on the master branch. Will publish the fix as soon as I have fixed another couple of things

**Comment by vinid** [comment] 2023-01-10 19:12
package should be updated now!

**Closed as completed** 2023-01-17 22:30 UTC

**Comment by IsaacBravo** [comment] 2023-01-18 07:56
Thanks!
